# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: beamr-envio
networks:
- id: 84532
  start_block: 0
  contracts:
  - name: BeamR
    address:
    - 0xf8405d14CF994017015fd94Db54C9D0899FD465B
    handler: src/EventHandlers.ts
    events:
    - event: Initialized(bytes32 adminRole, bytes32 rootAdminRole)
    - event: PoolCreated(address pool, address token, (bool,bool) config, address creator, bytes32 poolAdminRole, (uint256,string) metadata)
    - event: PoolMetadataUpdated(address pool, (uint256,string) metadata)
    - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
    - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
    - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
unordered_multichain_mode: true
field_selection: 
  transaction_fields:
    - from
    - hash